### ISSUE TITLE
Another navigator is already registered for this container

### ISSUE THREAD

**Issue by minhhoangzeno** [hoaphantn7604/react-native-curved-bottom-bar#10]
Mình gặp lỗi NavigatorContainer và Stack . Mình đã xem template của bạn, nhưng vẫn bị lỗi
![244553210_380042863791805_3690686852116108277_n](https://user-images.githubusercontent.com/83217409/136055748-6a9e6165-b58f-41be-8107-727fe901d837.jpg)
![image](https://user-images.githubusercontent.com/83217409/136055800-4b8e5de5-a799-474d-aa2c-e26c0008f2d9.png)
![image](https://user-images.githubusercontent.com/83217409/136055909-4e8cd9d1-0feb-4e01-be64-d35e02bf00a8.png)
![image](https://user-images.githubusercontent.com/83217409/136055952-d9a1bb2f-cd72-414f-9a57-1063f6494c28.png)

**Comment by hoaphantn7604** [comment]
Bạn không thể truyền 1 cái Stack Navigation vào bên trong <CurvedBottomBar.Screen> mà chỉ có thể truyền vào bên trong nó một JSX.Element

```
export default function App () {
  return( 
    <NavigationContainer/>
  )
}

function AppScreen () {
   ....
}

<Stack.Screen> name="main" component={AppScreen} options={{headerShow: false}} />

```

**Comment by minhhoangzeno** [comment]
Oh, mình cứ nghĩ CurvefBottomBar sẽ giống như Tab của thư viện react-navigation. Nếu chỉ truyền vào bên trong 1 JSX.Element thì mọi người không thể làm được nhiều Screen khác ở cùng một CurvedBottomBar rồi. Bạn có thể nâng cấp cải thiện được bài toán này không?. Mình xin góp ý, cảm ơn bạn.

**Comment by hoaphantn7604** [comment]
Bạn muốn navigate nhiều màn hình thì dùng Navigation.navigate thì đi bao nhiêu màn hình cũng được.

**Comment by hoaphantn7604** [comment]
Xem lại source demo của mình để xem cách navigate giữa nhiều màn hình.

**Comment by disizme** [comment]
@minhhoangzeno  
Hi, I have a similar issue. Did you find any solution or work around?
