### ISSUE TITLE
How to add appbar to the screens?

### ISSUE THREAD

**Issue by NibyP** [hoaphantn7604/react-native-curved-bottom-bar#14]
I want appbar to all screens with goback button. I couldn't find any options in the doc. Is this not included ?

**Comment by hoaphantn7604** [comment]
You can customize the header inside the element or I'm will add renderHeader props.

**Comment by NibyP** [comment]
@hoaphantn7604 Looking forward for renderHeader props.

**Comment by hoaphantn7604** [comment]
Okay, I will add renderHeader props.

**Comment by hoaphantn7604** [comment]
Please install later version 1.6.0.
Use renderHeader props customize your header.
