### ISSUE TITLE
Hiện tabbar ở tất cả màn hình

### ISSUE THREAD

**Issue by nongdinhtuyen** [hoaphantn7604/react-native-curved-bottom-bar#15]
Làm như nào hiện tabbar ở tất cả các màn vậy bạn. Mình có làm theo code bạn rồi nhưng khi vào những màn khác không thuộc tabbar thì không còn nữa. Ở trong <CurvedBottomBar.Screen> không cho truyền stack navigation mà chỉ truyền jsx thì mình không biết làm kiểu gì để cho cái tabbar hiện ở tất cả màn hình.

**Comment by hoaphantn7604** [comment]
Hiện tại gói này không hỗ trợ tabbar khắp tất cả các màn hình
