### ISSUE TITLE
Tab change animation / scroll effect issue

### ISSUE THREAD

**Issue by NxsHbb** [hoaphantn7604/react-native-curved-bottom-bar#18]
Suppose I have 4 screens. 
Screen 1, Screen2, Screen3 & Screen4
Currently my Active tab is Screen1. In this stage, if i go to Screen4 by pressing the tabbar icon, the animation is Screen1>Screen2>Screen3>Screen4.
But It Should be Screen1> Screen4

Can it be solved?

**Comment by NxsHbb** [comment]
@hoaphantn7604 Please help

**Comment by hoaphantn7604** [comment]
Hi @NxsHbb ,
I’m working on it.

**Comment by NxsHbb** [comment]
> Hi @NxsHbb , I’m working on it.

Please fix this please.

**Comment by hoaphantn7604** [comment]
hi @NxsHbb ,
react-native-pager-view does not support. I'm looking for another solution.

**Comment by hoaphantn7604** [comment]
hi @NxsHbb ,
Issue resolved, Please install later version 1.7.1
