### ISSUE TITLE
How can I prevent Rerender if I swipe or press a tab ?

### ISSUE THREAD

**Issue by shop-fluencer** [hoaphantn7604/react-native-curved-bottom-bar#22]
Hello,

I have 5 tabs. (Home,shopping,news,settings,profile)

In my profile component I use a console.log statement.

So if I swipe to any tab or if I press any tap I see my console log statement. Thats means its rerender wherever I am not on the current profile Tab. How can I prevent this ?

**Comment by hoaphantn7604** [comment]
Hi @shop-fluencer ,
You can use useMemo or useCallback.

**Comment by hoaphantn7604** [comment]
This issue has been resolved in version 2.0.0.

**Comment by masa2el** [comment]
still re-render all screens when tab on anyone

**Comment by Sulaiman122** [comment]
yeah me too, tried 
```
component={React.memo(() => (
            <Profile />
        ))}
```
reduce rerenders but still there is rerenders
