### ISSUE TITLE
box shadow question

### ISSUE THREAD

**Issue by baesumin** [hoaphantn7604/react-native-curved-bottom-bar#3]
hello,
Is there a way to put a shadow in bottom navigation? [type:'down']
If yes, please show an example.

**Comment by hoaphantn7604** [comment]
Thank you. I'm working on it.

**Comment by hoaphantn7604** [comment]
Please install version 1.0.5. Use strokeWidth={2} as a workaround.

**Comment by baesumin** [comment]
thanks
