### ISSUE TITLE
Not showing TabItem

### ISSUE THREAD

**Issue by Patel-Ruchita** [hoaphantn7604/react-native-curved-bottom-bar#30]
TabItem not showing on tabbar

![Simulator Screen Shot - iPhone 11 - 2022-06-24 at 13 51 20](https://user-images.githubusercontent.com/86362548/175495584-20cde690-e574-4901-b3da-a25b52277f05.png)

**Comment by joshkleyman** [comment]
I was having the same issue. If you copy/pasted the example nearly word for word, ensure that your "position" on your CurvedBottomBar.Screen components is in ALL CAPS.

<CurvedBottomBar.Screen
    ...
    position="LEFT"
    options={{ headerShown: false }}    // This is also available to you. Using this and the above in all caps fixed the bug for me.
>
