### ISSUE TITLE
@react-navigation/bottom-tabs could not be found

### ISSUE THREAD

**Issue by AshaKaligatla** [hoaphantn7604/react-native-curved-bottom-bar#34]
<img width="1163" alt="Screenshot 2022-07-20 at 7 22 51 PM" src="https://user-images.githubusercontent.com/89839665/180055098-ecaa2d1f-ed90-4516-9d84-a1bcfab224d2.png">
<img width="1440" alt="Screenshot 2022-07-20 at 11 44 37 PM" src="https://user-images.githubusercontent.com/89839665/180055113-9487c372-e21c-4f70-b481-72e46c6df226.png">

**Comment by AshaKaligatla** [comment]
This can also happen if there are multiple copies of '@react-navigation' packages installed.

this kind of error i'm getting again and again from last 72 hours i'm unable see my screens

**Comment by hoaphantn7604** [comment]
hi @AshaKaligatla ,
Is your problem solved yet?
Looks like you haven't configured react navigation.
```js
import { NavigationContainer } from '@react-navigation/native';
<NavigationContainer>
   <CurvedBottomBar.Navigator>
      ...
   </CurvedBottomBar.Navigator>
</NavigationContainer>
```
