### ISSUE TITLE
Screen does not navigate in IOS while using RTL

### ISSUE THREAD

**Issue by saudrehan279** [hoaphantn7604/react-native-curved-bottom-bar#35]
Everything is working great in android but when using RTL in IOS, screen does not navigate.

**Comment by hoaphantn7604** [comment]
hi @saudrehan279 ,
This issue cannot reproduce.

**Comment by saudrehan279** [comment]
> hi @saudrehan279 ,
> This issue cannot reproduce.

Thanks for your attention. I fixed the issue by upgrading to latest version. Thanks
