### ISSUE TITLE
How can I hide the bottom bar on other screens of Navigation Stack?

### ISSUE THREAD

**Issue by iamsaadMehmood** [hoaphantn7604/react-native-curved-bottom-bar#36]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-12 at 16 03 03](https://user-images.githubusercontent.com/101876738/184341599-29ca37a0-03d9-4bcb-a7dc-1d302ff45b55.png)
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-12 at 16 03 07](https://user-images.githubusercontent.com/101876738/184341616-5779aa2a-38c8-4785-aa00-5530f7cdd19b.png)

I want to show the bottom bar on only the product listing Screen and hide it on the product detail Screen (Show the bottom bar on the First Screen of the Navigation Stack but hide them on another screen of the Stack).
I have tried 
navigation.getParent()?.setOptions({tabBarStyle: {display: 'none'}});

but it's not working.

**Comment by iamsaadMehmood** [comment]
hi @hoaphantn7604,
Sure and Thanks for replying

**Comment by hoaphantn7604** [comment]
hi @iamsaadMehmood ,
Now has more method setVisible. Used to hide/show the tab bar. Ex: ref.current.setVisible(false).
Please install later version (2.1.0).

**Comment by Amitdutta121** [comment]
Can you be a little more descriptive about how to use the setVisible method?

**Comment by hoaphantn7604** [comment]
Hi @Amitdutta121 ,
Use react Ref. Call method ref.current.setVisible(false) to hidden, ref.current.setVisible(true) to show.

**Comment by Amitdutta121** [comment]
How to get the ref of the bottom tab?

**Comment by iamsaadMehmood** [comment]
@hoaphantn7604  we can use it by navigation.getParent()?.setVisible(false) right??

**Comment by Amitdutta121** [comment]
not able to use it this way cause it says "undefined" is not a function

**Comment by hoaphantn7604** [comment]
hi All,
Refer Ex:
```js
import React from 'react';
import { Alert, Animated, TouchableOpacity, View } from 'react-native';
import { CurvedBottomBar } from 'react-native-curved-bottom-bar';
import { scale } from 'react-native-size-scaling';
import Ionicons from 'react-native-vector-icons/Ionicons';
import HomeScreen from 'screens/home';
import SettingScreen from 'screens/setting';
import { styles } from './styles';

export const bottomBarRef = React.createRef<any>();
// bottomBarRef.current.setVisible(false); //Hidden
// bottomBarRef.current.setVisible(false); //Visible

export const tabBar = () => {
  const _renderIcon = (routeName: string, selectedTab: string) => {
    let icon = '';

    switch (routeName) {
      case 'title1':
        icon = 'ios-home-outline';
        break;
      case 'title2':
        icon = 'settings-outline';
        break;
    }

    return <Ionicons name={icon} size={scale(25)} color={routeName === selectedTab ? 'black' : 'gray'} />;
  };
  const renderTabBar = ({ routeName, selectedTab, navigate }: any) => {
    return (
      <TouchableOpacity
        onPress={() => navigate(routeName)}
        style={{
          flex: 1,
          alignItems: 'center',
          justifyContent: 'center',
        }}>
        {_renderIcon(routeName, selectedTab)}
      </TouchableOpacity>
    );
  };

  return (
    <View style={{ flex: 1 }}>
      <CurvedBottomBar.Navigator
        ref={bottomBarRef}
        style={styles.bottomBar}
        strokeWidth={0.5}
        height={scale(55)}
        circleWidth={scale(55)}
        bgColor="white"
        initialRouteName="title1"
        renderCircle={({ selectedTab, navigate }) => (
          <Animated.View style={styles.btnCircle}>
            <TouchableOpacity
              style={{
                flex: 1,
                justifyContent: 'center',
              }}
              onPress={() => Alert.alert('Click Action')}>
              <Ionicons name={'apps-sharp'} color="gray" size={scale(25)} />
            </TouchableOpacity>
          </Animated.View>
        )}
        tabBar={renderTabBar}>
        <CurvedBottomBar.Screen name="title1" position="LEFT" component={({ navigate }) => <HomeScreen />} />
        <CurvedBottomBar.Screen name="title2" position="RIGHT" component={({ navigate }) => <SettingScreen />} />
      </CurvedBottomBar.Navigator>
    </View>
  );
};

```

**Comment by Amitdutta121** [comment]
Thank you for the clarification.

**Comment by amit-bs23** [comment]
@iamsaadMehmood I faced a problem where Touchable opacity is not working on top of the screen after using this library. Manly, if you had any button at the top of the screen, the android touch event does not register. Did you face such problems?

**Comment by hoaphantn7604** [comment]
> @iamsaadMehmood I faced a problem where Touchable opacity is not working on top of the screen after using this library. Manly, if you had any button at the top of the screen, the android touch event does not register. Did you face such problems?

Re-check with later version 2.1.1

**Comment by vipulchakravarthy** [comment]
@hoaphantn7604 @iamsaadMehmood 

> hi All, Refer Ex:
> 
> ```js
> import React from 'react';
> import { Alert, Animated, TouchableOpacity, View } from 'react-native';
> import { CurvedBottomBar } from 'react-native-curved-bottom-bar';
> import { scale } from 'react-native-size-scaling';
> import Ionicons from 'react-native-vector-icons/Ionicons';
> import HomeScreen from 'screens/home';
> import SettingScreen from 'screens/setting';
> import { styles } from './styles';
> 
> export const bottomBarRef = React.createRef<any>();
> // bottomBarRef.current.setVisible(false); //Hidden
> // bottomBarRef.current.setVisible(false); //Visible
> 
> export const tabBar = () => {
>   const _renderIcon = (routeName: string, selectedTab: string) => {
>     let icon = '';
> 
>     switch (routeName) {
>       case 'title1':
>         icon = 'ios-home-outline';
>         break;
>       case 'title2':
>         icon = 'settings-outline';
>         break;
>     }
> 
>     return <Ionicons name={icon} size={scale(25)} color={routeName === selectedTab ? 'black' : 'gray'} />;
>   };
>   const renderTabBar = ({ routeName, selectedTab, navigate }: any) => {
>     return (
>       <TouchableOpacity
>         onPress={() => navigate(routeName)}
>         style={{
>           flex: 1,
>           alignItems: 'center',
>           justifyContent: 'center',
>         }}>
>         {_renderIcon(routeName, selectedTab)}
>       </TouchableOpacity>
>     );
>   };
> 
>   return (
>     <View style={{ flex: 1 }}>
>       <CurvedBottomBar.Navigator
>         ref={bottomBarRef}
>         style={styles.bottomBar}
>         strokeWidth={0.5}
>         height={scale(55)}
>         circleWidth={scale(55)}
>         bgColor="white"
>         initialRouteName="title1"
>         renderCircle={({ selectedTab, navigate }) => (
>           <Animated.View style={styles.btnCircle}>
>             <TouchableOpacity
>               style={{
>                 flex: 1,
>                 justifyContent: 'center',
>               }}
>               onPress={() => Alert.alert('Click Action')}>
>               <Ionicons name={'apps-sharp'} color="gray" size={scale(25)} />
>             </TouchableOpacity>
>           </Animated.View>
>         )}
>         tabBar={renderTabBar}>
>         <CurvedBottomBar.Screen name="title1" position="LEFT" component={({ navigate }) => <HomeScreen />} />
>         <CurvedBottomBar.Screen name="title2" position="RIGHT" component={({ navigate }) => <SettingScreen />} />
>       </CurvedBottomBar.Navigator>
>     </View>
>   );
> };
> ```

<img width="356" alt="Screenshot 2022-09-26 at 11 16 43 PM" src="https://user-images.githubusercontent.com/41899503/192345302-12ec16a7-9f7f-4e0d-8e83-0b7110dc4aee.png">
Even after updating to the latest version getting the same error.

**Comment by Munir-Hassan** [comment]
> @hoaphantn7604 @iamsaadMehmood
> 
> > hi All, Refer Ex:
> > ```js
> > import React from 'react';
> > import { Alert, Animated, TouchableOpacity, View } from 'react-native';
> > import { CurvedBottomBar } from 'react-native-curved-bottom-bar';
> > import { scale } from 'react-native-size-scaling';
> > import Ionicons from 'react-native-vector-icons/Ionicons';
> > import HomeScreen from 'screens/home';
> > import SettingScreen from 'screens/setting';
> > import { styles } from './styles';
> > 
> > export const bottomBarRef = React.createRef<any>();
> > // bottomBarRef.current.setVisible(false); //Hidden
> > // bottomBarRef.current.setVisible(false); //Visible
> > 
> > export const tabBar = () => {
> >   const _renderIcon = (routeName: string, selectedTab: string) => {
> >     let icon = '';
> > 
> >     switch (routeName) {
> >       case 'title1':
> >         icon = 'ios-home-outline';
> >         break;
> >       case 'title2':
> >         icon = 'settings-outline';
> >         break;
> >     }
> > 
> >     return <Ionicons name={icon} size={scale(25)} color={routeName === selectedTab ? 'black' : 'gray'} />;
> >   };
> >   const renderTabBar = ({ routeName, selectedTab, navigate }: any) => {
> >     return (
> >       <TouchableOpacity
> >         onPress={() => navigate(routeName)}
> >         style={{
> >           flex: 1,
> >           alignItems: 'center',
> >           justifyContent: 'center',
> >         }}>
> >         {_renderIcon(routeName, selectedTab)}
> >       </TouchableOpacity>
> >     );
> >   };
> > 
> >   return (
> >     <View style={{ flex: 1 }}>
> >       <CurvedBottomBar.Navigator
> >         ref={bottomBarRef}
> >         style={styles.bottomBar}
> >         strokeWidth={0.5}
> >         height={scale(55)}
> >         circleWidth={scale(55)}
> >         bgColor="white"
> >         initialRouteName="title1"
> >         renderCircle={({ selectedTab, navigate }) => (
> >           <Animated.View style={styles.btnCircle}>
> >             <TouchableOpacity
> >               style={{
> >                 flex: 1,
> >                 justifyContent: 'center',
> >               }}
> >               onPress={() => Alert.alert('Click Action')}>
> >               <Ionicons name={'apps-sharp'} color="gray" size={scale(25)} />
> >             </TouchableOpacity>
> >           </Animated.View>
> >         )}
> >         tabBar={renderTabBar}>
> >         <CurvedBottomBar.Screen name="title1" position="LEFT" component={({ navigate }) => <HomeScreen />} />
> >         <CurvedBottomBar.Screen name="title2" position="RIGHT" component={({ navigate }) => <SettingScreen />} />
> >       </CurvedBottomBar.Navigator>
> >     </View>
> >   );
> > };
> > ```
> 
> <img alt="Screenshot 2022-09-26 at 11 16 43 PM" width="356" src="https://user-images.githubusercontent.com/41899503/192345302-12ec16a7-9f7f-4e0d-8e83-0b7110dc4aee.png">
> 
> Even after updating to the latest version getting the same error.

@vipulchakravarthy Did you find any solution to it? please let me know. I am facing the same issue. TIA

**Comment by hoaphantn7604** [comment]
hi @vipulchakravarthy & @Munir-Hassan ,

We need to check if the tabBarRef is initialized before calling the function. tabBarRef?.current?.setVisible()

```js
  import React, { createRef } from 'react'; // <== import createRef
  import {
    Alert,
    Animated,
    StyleSheet,
    TouchableOpacity,
    View,
  } from 'react-native';
  import { CurvedBottomBar } from 'react-native-curved-bottom-bar';
  import Ionicons from 'react-native-vector-icons/Ionicons';
  import { NavigationContainer } from '@react-navigation/native';

  export const tabBarRef: any = createRef(); // <== Call this function to hide tabbar tabBarRef?.current?.setVisible();

  export const tabBar = () => {
    const _renderIcon = (routeName: string, selectedTab: string) => {
      let icon = '';

      switch (routeName) {
        case 'title1':
          icon = 'ios-home-outline';
          break;
        case 'title2':
          icon = 'settings-outline';
          break;
      }

      return (
        <Ionicons
          name={icon}
          size={25}
          color={routeName === selectedTab ? 'black' : 'gray'}
        />
      );
    };
    const renderTabBar = ({ routeName, selectedTab, navigate }: any) => {
      return (
        <TouchableOpacity
          onPress={() => navigate(routeName)}
          style={{
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
          }}>
          {_renderIcon(routeName, selectedTab)}
        </TouchableOpacity>
      );
    };

    return (
      <View style={{ flex: 1 }}>
        <NavigationContainer>
          <CurvedBottomBar.Navigator
            ref={tabBarRef} // <== Add line
            style={styles.bottomBar}
            strokeWidth={0.5}
            strokeColor="#DDDDDD"
            height={55}
            circleWidth={55}
            bgColor="white"
            initialRouteName="title1"
            borderTopLeftRight
            renderCircle={({ selectedTab, navigate }) => (
              <Animated.View style={styles.btnCircle}>
                <TouchableOpacity
                  style={{
                    flex: 1,
                    justifyContent: 'center',
                  }}
                  onPress={() => Alert.alert('Click Action')}>
                  <Ionicons name={'apps-sharp'} color="gray" size={25} />
                </TouchableOpacity>
              </Animated.View>
            )}
            tabBar={renderTabBar}>
            <CurvedBottomBar.Screen
              name="title1"
              position="LEFT"
              component={() => (
                <View style={{ backgroundColor: '#BFEFFF', flex: 1 }} />
              )}
            />
            <CurvedBottomBar.Screen
              name="title2"
              component={() => (
                <View style={{ backgroundColor: '#FFEBCD', flex: 1 }} />
              )}
              position="RIGHT"
            />
          </CurvedBottomBar.Navigator>
        </NavigationContainer>
      </View>
    );
  };

  export const styles = StyleSheet.create({
    container: {
      flex: 1,
      padding: 20,
    },
    button: {
      marginVertical: 5,
    },
    bottomBar: {},
    btnCircle: {
      width: 60,
      height: 60,
      borderRadius: 35,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'white',
      padding: 10,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 0.5,
      },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,
      elevation: 1,
      bottom: 30,
    },
    imgCircle: {
      width: 30,
      height: 30,
      tintColor: 'gray',
    },
    img: {
      width: 30,
      height: 30,
    },
  });
```

**Comment by iamhaaamed** [comment]
not working for me. even if i try to log the ```tabBarRef```, I will get this error:
```ERROR  Error: Couldn't find a 'component', 'getComponent' or 'children' prop for the screen 'Notifications'. This can happen if you passed 'undefined'. You likely forgot to export your component from the file it's defined in, or mixed up default import and named import when importing.```
