### ISSUE TITLE
Middle circle icon does not highlight on focus as a screen link

### ISSUE THREAD

**Issue by hochdyl** [hoaphantn7604/react-native-curved-bottom-bar#39]
Hi,

In my project, I use the middle circle icon as a navigation link to another screen. Everything is working fine.
However, this render circle method does not handle a route name parameter since it's not rendering by the tabBar method.

See below a gif demo.

![screen-capture](https://user-images.githubusercontent.com/55688853/188611758-e6a70afb-0935-4649-b41f-1f0898415f69.gif)

Usual "renderTabBar" : 
```
<CurvedBottomBar.Navigator
      ...
      tabBar={renderTabBar}
      ...
>
                    
function renderTabBar({ routeName, selectedTab, navigate }: any) {
    return (
        <Pressable
            onPress={() => navigate(routeName)}
            style={{
                flex: 1,
                alignItems: 'center',
                justifyContent: 'center',
            }}>
            {_renderIcon(routeName, selectedTab)}
        </Pressable>
    );
}
```

Specific "renderCircle" : 
```
<CurvedBottomBar.Navigator
      ...
      renderCircle={renderCircle}
      ...
>

function renderCircle({ selectedTab, navigate }: any) {
    return (
        <Animated.View style={navigationBarStyle.btnCircle}>
            <Pressable
                style={navigationBarStyle.btnCirclePressable}
                onPress={() => navigate(selectedTab)}>
                <Ionicons name={'chatbubbles-outline'} color={iconColor} size={25} />
            </Pressable>
        </Animated.View>
    );
}
```

This is an issue for me because when I navigate to my screen with this middle button, I cannot verify if the current route name is matched to highlight the icon.

This is the expected result : 

![captures_chrome-capture-2022-8-6](https://user-images.githubusercontent.com/55688853/188610330-385ad0c5-09e7-406a-8111-f2f1b1b7dea2.png)

**Comment by hoaphantn7604** [comment]
hi @hochdyl ,
You can show full code for me to support?

**Comment by hoaphantn7604** [comment]
hi @hochdyl ,
This issue is resolved.
Please install later version.
Refer example:
```js
   function renderCircle({routeName, selectedTab, navigate}: any) {
        return (
            <Animated.View style={styles.btnCircle}>
                <Pressable
                    style={styles.btnCirclePressable}
                    onPress={() => navigate(selectedTab)}>
                    <Ionicons name={'chatbubbles-outline'} color={routeName === selectedTab ? 'blue' : 'gray'} size={25}/>
                </Pressable>
            </Animated.View>
        );
    }
```

**Comment by hochdyl** [comment]
It's working perfectly now, thanks for your quick support !
