### ISSUE TITLE
objects must have a [Symbol.iterator]() method.

### ISSUE THREAD

**Issue by kampretosjr** [hoaphantn7604/react-native-curved-bottom-bar#4]
i copied everything in usage section and installing needed dependencies 
but its ended in 
```
Invalid attempt to destructure non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]) method.
```
![image](https://user-images.githubusercontent.com/33866110/129375858-42023f9b-461c-4056-9d51-e1f8f69f6220.png)
how can i solve this ?
and when i hover to Navigator on CurvedBottom.Navigator its return 'any' ,not the exact location 
![image](https://user-images.githubusercontent.com/33866110/129377172-38bdb766-25fb-4609-98d8-40b62fa4d467.png)

**Comment by hoaphantn7604** [comment]
Are you using my example code?

**Comment by tungnguyenit0201** [comment]
i used your example code and got same issue

**Comment by NibyP** [comment]
Any solutions? I got the same issue.

**Comment by NibyP** [comment]
I changed `const [type, setType] = useState<'down' | 'up'>('down'); ` to ` const [type, setType] = useState('up');`
Now error is gone.

**Comment by hoaphantn7604** [comment]
I’m working on it.

**Comment by hoaphantn7604** [comment]
https://github.com/hoaphantn7604/react-native-template-components
Try using the example in this template to see if you have the same problem?
