### ISSUE TITLE
Change "line" color

### ISSUE THREAD

**Issue by Lucasmellof** [hoaphantn7604/react-native-curved-bottom-bar#40]
Hi,

I'd like to change (or disable) the line color of the navigator.  
I use dark colors on my app and it is a little bit strange to have a white line.

https://github.com/hoaphantn7604/react-native-curved-bottom-bar/blob/8f1a7cb2a601693be52b1526b287886b4c101016/src/CurvedBottomBar/components/navigator/index.tsx#L122

![image](https://user-images.githubusercontent.com/23638982/192125532-539ce6a3-b651-4869-a4a0-7b26e50babd4.png)

**Comment by hoaphantn7604** [comment]
Hi @Lucasmellof ,
Can you set strokeWidth={0} to disable line.

**Comment by Lucasmellof** [comment]
I opened a PR adding an option to change the color: https://github.com/hoaphantn7604/react-native-curved-bottom-bar/pull/41
