### ISSUE TITLE
Remove left & right curve

### ISSUE THREAD

**Issue by whatoken** [hoaphantn7604/react-native-curved-bottom-bar#46]
Hello,

I'm not familiar with **d3-shape**. 

Can you please help me how to remove the curve of left and right of bottom bar? Just keep the curve for center.

**Comment by hoaphantn7604** [comment]
hi @whatoken ,
Refer this code:
```js
<CurvedBottomBar.Navigator
  ...
   borderTopLeftRight ={false}
>
```
