### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by bars0um** [hoaphantn7604/react-native-curved-bottom-bar#47]
Hi, 

Thanks for this really useful library. I'm having a minor issue which is that it throws this warning regardless of what I do.

The warning is: "Warning: Each child in a list should have a unique "key" prop." and you should be able to reproduce by simply running the example code.

Appreciate if you have any workarounds.

Cheers!

**Comment by hoaphantn7604** [comment]
hi @bars0um ,
What version are you using?

**Comment by bars0um** [comment]
Looks like I'm using 2.0.0, let me give it a go with the latest version and
get back to you!

**Comment by bars0um** [comment]
Hi @hoaphantn7604,

I've just tested with the latest version but I get the same error...

We use a very similar setup to the example code, in fact I can reproduce the error with the example code.

```
 ERROR  Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ForwardRef`. See https://reactjs.org/link/warning-keys for more information.
    at Screen
    in Unknown (at TabStackScreen.js:94)
    in TabStackScreen (at SceneView.tsx:132)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:124)
    in SceneView (at useDescriptors.tsx:217)
    in RCTView (at View.js:32)
   
```

**Comment by bars0um** [comment]
Yes it looks like 2.1.4 fixes the issue!
