### ISSUE TITLE
Is there a way to customise the centre floating button to be moved to the right end of the view?

### ISSUE THREAD

**Issue by kiranNegiloni** [hoaphantn7604/react-native-curved-bottom-bar#51]
Hi Team, Many thanks for the wonderful library, I have got a design to be developed where the action button should be placed at the right end of the screen, I have attached the design for your reference. Please provide some input on the svg path. I am not able to modify it to match the design.

![Subtraction 66](https://user-images.githubusercontent.com/31494592/216773959-b3d160c7-2c8a-42f9-8884-547d5f77dfd4.png)

**Comment by hoaphantn7604** [comment]
hi @kiranNegiloni ,

This feature is completed and being testing before release.

![ezgif com-crop](https://user-images.githubusercontent.com/50919571/219710503-ca9e8c6e-36a8-4565-9e03-2ec11148bca2.png)

**Comment by hoaphantn7604** [comment]
This issue is resolved. Please install version 3.0.0.

**Comment by kiranNegiloni** [comment]
Thanks Alot @hoaphantn7604. Really appreciate the efforts you are putting for contributing to the community. I will try this.
