### ISSUE TITLE
react-native-curved-bottom-bar doesn't seem to be linked.make sure:

### ISSUE THREAD

**Issue by arun-saleth** [hoaphantn7604/react-native-curved-bottom-bar#54]
Error: The package 'react-native-curved-bottom-bar' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo Go

**Comment by cyberdavinci** [comment]
Having same error using expo

**Comment by HardMode2015** [comment]
same error here after upgrade expo and react native

**Comment by hoaphantn7604** [comment]
Hi all,
What is the version of this library you are using?

**Comment by hoaphantn7604** [comment]
> @hoaphantn7604
> 
> I am facing issue 3.1.0 version.
> 
> But if i use below commend it will working fine. npm i react-native-curved-bottom-bar@3.0.0

Okay! I’m working on it.

**Comment by hoaphantn7604** [comment]
hi All,

This issue is resolved. Please install new version.
Refer this example https://github.com/hoaphantn7604/react-native-curved-bottom-bar#use-in-expo

**Comment by arun-saleth** [comment]
@hoaphantn7604 Thank you so much
