### ISSUE TITLE
Can we add borderColor and borderWidth to curved tab

### ISSUE THREAD

**Issue by abdulrafeh857** [hoaphantn7604/react-native-curved-bottom-bar#58]
Can we add borderColor and borderWidth to curved tab? so that only the top curved part has a borderColor visible.

![Simulator Screen Shot - iPhone 11 Pro Max - 2023-04-02 at 03 57 00](https://user-images.githubusercontent.com/37897250/229319854-8891e9ce-889a-4b6c-ba7d-1954d47724b1.png)

**Comment by hoaphantn7604** [comment]
hi @abdulrafeh857 ,
In version 2.1.4, you have the option to utilize the props strokeColor and strokeWidth.
Starting from version 3.0.0, I have removed those props and substituted them with the shadow color.

**Comment by abdulrafeh857** [comment]
so I have to downgrade? Is there any way we can add both of these props?

**Comment by hoaphantn7604** [comment]
I will add the "borderColor" and "borderWidth" props in the next version.

**Comment by Jamal-ReachFirst** [comment]
You can use strokeWidth and strokeColor for now

**Comment by abdulrafeh857** [comment]
Thank you

**Comment by MMYurt** [comment]
Hi @hoaphantn7604,

I used "strokeWidth" and "strokeColor" props to achieve this on v2. I've upgraded the version and can't use them anymore. You mentioned that "borderColor" and "borderWidth" props will come instead. It seems they haven't been added. Do you have any updates on this issue? Should we downgrade the version?
