### ISSUE TITLE
Mình bị lỗi loading tất cả các tab trong bottom ? làm sao tắt chế độ loading tất cả các tab dc nhỉ

### ISSUE THREAD

**Issue by hieunvph12545** [hoaphantn7604/react-native-curved-bottom-bar#8]
<CurvedBottomBar.Screen
                name="home"
                position="left"
                component={(navigate )=> <HomeScreen navigate={navigate} />}
            />
            <CurvedBottomBar.Screen
                name="events"
                component={(navigate )=> <EventsScreen navigate={navigate} />}
                position="left"
            />

**Comment by hoaphantn7604** [comment]
Hiện tại vẫn chưa có tính năng lazy load, mình sẽ xem xét lại yêu cầu này.

**Comment by hoaphantn7604** [comment]
Tính năng lazy đã được bổ xung, vui lòng cài version mới nhất 1.4.0. Và xem các hướng dẫn trong Documents.
