### ISSUE TITLE
Circle open screen

### ISSUE THREAD

**Issue by minhhoangzeno** [hoaphantn7604/react-native-curved-bottom-bar#9]
<img width="351" alt="Screen Shot 2021-10-04 at 17 24 52" src="https://user-images.githubusercontent.com/83217409/135835341-4cc72871-5777-4b91-ad25-9c2369943817.png">
Mình muốn khi ấn vào hình tròn ở giữa hiện ra 1 tab khác chứ không hiện alert này thì làm thế nào ạ

**Comment by hoaphantn7604** [comment]
Nó là cái button không phải 1 tab nha bạn.

**Comment by minhhoangzeno** [comment]
vâng, bạn có thể gợi ý cho mình biết thư viện nào khác mà custom bottom tab bar như của bạn và hình tròn ở giữa là tab không ạ. Giá như thư viện này của bạn, nút tròn là tab thì hay biết mấy. :D

**Comment by hoaphantn7604** [comment]
Bạn có thực sự cần tính năng này cho dự án không, nếu nó thật sự quan trọng mình sẽ custom cho bạn

**Comment by hoaphantn7604** [comment]
Mình đã custom yêu cầu của bạn trong version 1.5.0.

Bạn thêm code này vào giữa các tab "left" và "right".
```
 <CurvedBottomBar.Screen
      name="title1"
      component={({ navigate }) => <View style={{ backgroundColor: '#FFEBCD', flex: 1 }} />}
      position="left"
 />
 <CurvedBottomBar.Screen
      name="center"
      component={({ navigate }) => <View style={{ backgroundColor: '#FFEBCD', flex: 1 }} />}
      position="center"
 />
 <CurvedBottomBar.Screen
      name="title2"
      component={({ navigate }) => <View style={{ backgroundColor: '#FFEBCD', flex: 1 }} />}
      position="right"
 />
```

**Comment by minhhoangzeno** [comment]
Tính năng này thật sự rất hữu ích, thiết kế của bạn rất phù hợp. Nhưng mình thêm code như bạn thì vẫn chưa nhận được đúng ý của mình. Phiền bạn xem giúp mình nhé. 
![image](https://user-images.githubusercontent.com/83217409/135863191-081d3adb-8c95-44f4-a1e8-742d759ebf07.png)
![image](https://user-images.githubusercontent.com/83217409/135863303-4d687f94-1eeb-4a33-a7e8-f71a26f73fd3.png)
![image](https://user-images.githubusercontent.com/83217409/135863329-94911c2a-61bf-4c6b-9485-bf1db43c247e.png)

**Comment by minhhoangzeno** [comment]
Mình vẫn thấy hình tròn ở giữa khi ấn vào mà vẫn alert button , chưa chuyển sang màn khác bạn ạ.

**Comment by hoaphantn7604** [comment]
Bạn xem code mẫu này.

<img width="791" alt="Screen Shot 2021-10-04 at 21 03 29" src="https://user-images.githubusercontent.com/50919571/135865479-579c7f94-c623-4cce-8707-5e7db25d6e89.png">

**Comment by hoaphantn7604** [comment]
```
<CurvedBottomBar.Navigator
  ref={ref}
  type={type}
  height={60}
  circleWidth={55}
  bgColor="white"
  borderTopLeftRight={true}
  strokeWidth={2}
  swipeEnabled={true}
  initialRouteName="title1"
  renderCircle={({ selectTab, navigate }) => (
    <TouchableOpacity
      style={styles.btnCircle} onPress={navigate('center')}>
      <Ionicons name="sync-outline" size={26} />
    </TouchableOpacity>
  )}
  tabBar={({ routeName, selectTab, navigate }) => {
    return (
      <TouchableOpacity
        onPress={() => navigate(routeName)}
        style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        {_renderIcon(routeName, selectTab)}
      </TouchableOpacity>
    );
  }}>
  <CurvedBottomBar.Screen
    name="title1"
    position="left"
    component={({ navigate }) => <View style={{ backgroundColor: '#BFEFFF', flex: 1 }} />}
  />
  <CurvedBottomBar.Screen
    name="center"
    component={({ navigate }) => <View style={{ backgroundColor: '#FFEBCD', flex: 1 }} />}
    position="center"
  />
  <CurvedBottomBar.Screen
    name="title2"
    component={({ navigate }) => <View style={{ backgroundColor: '#FFEBCD', flex: 1 }} />}
    position="left"
  />
</CurvedBottomBar.Navigator>
```

**Comment by minhhoangzeno** [comment]
Mình thử được rồi bạn ạ, thực sự cảm ơn bạn. Mình xin hỏi thêm một vấn đề nữa, mình có xem ở issuses trước đó mà mình thay vào của mình thì lại chưa được. Mình để 2 Stack.Navigator ở dưới CurvedBottomBar thì gặp lỗi. 
![image](https://user-images.githubusercontent.com/83217409/135869865-57a14a11-6d5f-4a9c-b36c-2036be9e88f4.png)

![image](https://user-images.githubusercontent.com/83217409/135869734-084605f2-52d2-4e52-b546-e88c4b596519.png)
![image](https://user-images.githubusercontent.com/83217409/135869795-a7993e85-4476-4c13-961e-926776993c67.png)

**Comment by minhhoangzeno** [comment]
![244553210_380042863791805_3690686852116108277_n](https://user-images.githubusercontent.com/83217409/135870200-37a52597-cfc2-4997-ba1f-b820bc3e0bde.jpg)

Hiện lỗi thế này bạn ạ. Mong bạn xem giúp mình!

**Comment by hoaphantn7604** [comment]
"AppScreen" bạn dùng nó giống như một màn hình bình thường nằm bên trong stack navigation.

**Comment by hoaphantn7604** [comment]
https://github.com/hoaphantn7604/react-native-template-components
bạn có thể xem code mẫu ở đây.

**Comment by hoaphantn7604** [comment]
Nếu thấy package này hữu ích thì star nhé.

**Comment by minhhoangzeno** [comment]
Rất hữu ích bạn ạ, chắc chắn sẽ có nhiều người dùng thư viện này của bạn đó. Cảm ơn bạn đã lắng nghe và update version. :D

**Comment by hoaphantn7604** [comment]
Nếu còn issue gì bạn cứ tạo ticket.
